Repository Pouzor/dashboard-gitlabci, pull requests merged in 2018-04, with the labels that each got.

#1 Project structure and add bootstrap
  .env.dist
  .eslintignore
  .eslintrc.js
  .gitignore
  Makefile
  config/dev.env.js
  config/index.js
  config/prod.env.js
  config/test.env.js
  package.json
  src/App.vue
  src/assets/logo.png
  src/components/Body.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/Main.vue
  src/components/mr/MergeRequest.vue
  src/components/mr/MergeRequests.vue
  src/main.js
  src/router/index.js
  src/store/gitLab.js
Labels: enhancement

#9 Settings
  .eslintrc.js
  build/webpack.base.conf.js
  package-lock.json
  package.json
  src/App.vue
  src/components/Body.vue
  src/components/Footer.vue
  src/components/Main.vue
  src/components/header/Header.vue
  src/components/header/Settings.vue
  src/components/mr/MergeRequests.vue
  src/components/projects/Project.vue
  src/components/projects/Projects.vue
  src/main.js
  src/store/gitLab.js
Labels: MVP, enhancement

#11 Basic design on Ci and MR pages
  README.md
  package-lock.json
  src/components/mr/MergeRequest.vue
  src/components/mr/MergeRequests.vue
  src/components/projects/Project.vue
  src/components/projects/Projects.vue
  src/store/gitLab.js
Labels: Front, enhancement

#12 Create MR page
  src/components/Homepage.vue
  src/components/ci/CIIndex.vue
  src/components/mr/MRIndex.vue
  src/components/mr/MergeRequests.vue
  src/router/index.js
Labels: MVP, enhancement

#14 Use favorite projects
  .eslintrc.js
  package-lock.json
  package.json
  src/App.vue
  src/components/Homepage.vue
  src/components/header/Header.vue
  src/components/header/Settings.vue
  src/components/pipeline/Pipeline.vue
  src/components/pipeline/PipelineIndex.vue
  src/components/pipeline/Pipelines.vue
  src/components/projects/Projects.vue
  src/eventBus.js
  src/main.js
  src/router/index.js
  src/store/gitLab.js
  src/store/store.js
Labels: MVP, enhancement

#16 Mr work now on favorite project
  src/store/gitLab.js
Labels: enhancement

#17 Cleaned design
  package-lock.json
  package.json
  src/App.vue
  src/components/Footer.vue
  src/components/Homepage.vue
  src/components/mr/MergeRequest.vue
  src/components/pipeline/Pipeline.vue
  src/components/pipeline/Pipelines.vue
Labels: Front, enhancement
